### ISSUE TITLE
About the output of Flurry

### ISSUE THREAD

**Issue by bizhishui** [JacobCrabill/FlurryPP#1]
Hi Jacob,
I've just compiled your FlurryPP and run a Euler cylinder case, but I  found there are many duplicated output when I use mpirun. 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Iter    Time          rho           rhoU          rhoV          rhoW          rhoE          deltaT        CDinv         CLinv         CNinv         CDtot         CLtot         CNtot  
1       1.87469e-04   3.17401e+00   2.25229e-01   2.24342e-01   2.02235e-03   7.99850e+00   1.87469e-04   4.76757e-01   -3.10256e-04  -7.21911e-16  4.76757e-01   -3.10256e-04  -7.21911e-16  

Iter    Time          rho           rhoU          rhoV          rhoW          rhoE          deltaT        CDinv         CLinv         CNinv         CDtot         CLtot         CNtot  
1       1.87469e-04   3.17401e+00   2.25229e-01   2.24342e-01   2.02235e-03   7.99850e+00   1.87469e-04   4.76757e-01   -3.10256e-04  -7.21911e-16  4.76757e-01   -3.10256e-04  -7.21911e-16  

Iter    Time          rho           rhoU          rhoV          rhoW          rhoE          deltaT        CDinv         CLinv         CNinv         CDtot         CLtot         CNtot  
1       1.87469e-04   3.17401e+00   2.25229e-01   2.24342e-01   2.02235e-03   7.99850e+00   1.87469e-04   4.76757e-01   -3.10256e-04  -7.21911e-16  4.76757e-01   -3.10256e-04  -7.21911e-16  

Iter    Time          rho           rhoU          rhoV          rhoW          rhoE          deltaT        CDinv         CLinv         CNinv         CDtot         CLtot         CNtot  
1       1.87469e-04   3.17401e+00   2.25229e-01   2.24342e-01   2.02235e-03   7.99850e+00   1.87469e-04   4.76757e-01   -3.10256e-04  -7.21911e-16  4.76757e-01   -3.10256e-04  -7.21911e-16  
10      1.87452e-03   3.08395e+00   5.06344e-01   3.48668e-01   2.77790e-03   7.77063e+00   1.87318e-04   4.69828e+00   -3.06824e-03  -7.22214e-16  4.69828e+00   -3.06824e-03  -7.22214e-16  
10      1.87452e-03   3.08395e+00   5.06344e-01   3.48668e-01   2.77790e-03   7.77063e+00   1.87318e-04   4.69828e+00   -3.06824e-03  -7.22214e-16  4.69828e+00   -3.06824e-03  -7.22214e-16  
10      1.87452e-03   3.08395e+00   5.06344e-01   3.48668e-01   2.77790e-03   7.77063e+00   1.87318e-04   4.69828e+00   -3.06824e-03  -7.22214e-16  4.69828e+00   -3.06824e-03  -7.22214e-16  
10      1.87452e-03   3.08395e+00   5.06344e-01   3.48668e-01   2.77790e-03   7.77063e+00   1.87318e-04   4.69828e+00   -3.06824e-03  -7.22214e-16  4.69828e+00   -3.06824e-03  -7.22214e-16  
20      3.74100e-03   2.90986e+00   9.42392e-01   5.85515e-01   4.47696e-03   7.32898e+00   1.86123e-04   9.13178e+00   -6.00735e-03  -7.23075e-16  9.13178e+00   -6.00735e-03  -7.23075e-16  
20      3.74100e-03   2.90986e+00   9.42392e-01   5.85515e-01   4.47696e-03   7.32898e+00   1.86123e-04   9.13178e+00   -6.00735e-03  -7.23075e-16  9.13178e+00   -6.00735e-03  -7.23075e-16  
20      3.74100e-03   2.90986e+00   9.42392e-01   5.85515e-01   4.47696e-03   7.32898e+00   1.86123e-04   9.13178e+00   -6.00735e-03  -7.23075e-16  9.13178e+00   -6.00735e-03  -7.23075e-16  
20      3.74100e-03   2.90986e+00   9.42392e-01   5.85515e-01   4.47696e-03   7.32898e+00   1.86123e-04   9.13178e+00   -6.00735e-03  -7.23075e-16  9.13178e+00   -6.00735e-03  -7.23075e-16  
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

I checked in the code and found the output control "parmas->rank==0" do exists, so can you tell me how to correct that?
Thanks!

Best regards,
Maxime

**Comment by JacobCrabill** [comment]
Hi Maxime,

Are you certain that you compiled for MPI ('make mpi')?  The duplicate output should only happen if you run a serial program through mpirun/mpiexec.

-Jacob

**Comment by bizhishui** [comment]
Hi Jacob,
Yes, I'm sure that I using the command "make mpi", and I then running the test case by "mpirun -n 4 Flurry input*".  Besides, when I use "make release mpi=4", error occur in compiling the lib tioga (cannot find the mpi.h for codetypes.h).

Best regards,
Maxime

**Comment by JacobCrabill** [comment]
Using the 'release' build ("make release mpi=n") is only for serial compilation; and you must put an "n" as in "no", not a "4".

Have you tried "make clean && make -j mpi"?  (the -j just makes it compile much faster).  I can't think of any reason why this shouldn't work for you; it works just fine on all of my computers... you're using the latest version of the master branch?

**Comment by bizhishui** [comment]
Hi Jacob,

# I think there some errors in linking libmetis.a. When I use "make mpi" to the latest master branch, error show up as:

obj/geo.o: In function `geo::partitionMesh()':
geo.cpp:(.text+0x5f5f): undefined reference to`METIS_SetDefaultOptions'
collect2: error: ld returned 1 exit status

# make: **\* [Flurry] Error 1

I've checked the location of metis, which is the same with HiFi.
![flurrymakefile](https://cloud.githubusercontent.com/assets/8256788/10262756/3191055c-6a08-11e5-8e05-54646034e2f4.png)
Do you how that happen?

And also a question about the method "rs_to_ab" (in polynomials.cpp). The left hand of "ab.y = (2.0*((1.0+rs.x)/(1.0-rs.y))) - 1.0" should not be "ab.x" ?

Best regards,
Maxime

**Comment by bizhishui** [comment]
Hi Jacob,
I think I've found the errors.
1. In the makefile, $(LFLAGS) should be changed to $(CXXFLAGS).
2. In the input.cpp, "writeIBLANK" should be initialized for the "READ_MESH" case.

Best regards,
Maxime
