### ISSUE TITLE
mpi=n not compiling

### ISSUE THREAD

**Issue by bouloumag** [JacobCrabill/FlurryPP#3]
In a fresh clone, I try to build with 
% make release mpi=n

and get error about mpi stuff was not declared in this scope. See full listing attached.
[compil.txt](https://github.com/JacobCrabill/FlurryPP/files/79944/compil.txt)

I am using Ubuntu 14.04.3 LTS.

**Comment by JacobCrabill** [comment]
There was a missing #ifndef statement - should be fixed now!
