### ISSUE TITLE
NaN Encountered in Solution Residual

### ISSUE THREAD

**Issue by bouloumag** [JacobCrabill/FlurryPP#4]
After installing metis from Ubuntu 14.04.3 LTS repositories, updating makefile and compiling with 
% make mpi 
I get the following runtime error

% mpirun -n 1 bin/Flurry tests/advection/input_advect
[...]
Iter    Var  Residual

1       Res  8.896472e+110  
rank 0, ele 0:  minPt = -1.000000e+01,-1.000000e+01,0.000000e+00, maxPt = -9.000000e+00,-9.000000e+00,0.000000e+00
Fatal error 'NaN Encountered in Solution Residual!' at src/output.cpp:558

I also tried randomly tests/euler/vortex/input_vortex which seems to work fine.

**Comment by JacobCrabill** [comment]
Found the bug - should be good now.

**Comment by JacobCrabill** [comment]
The issue is with scalar advection-diffusion in MPI cases... I'm looking into the issue, but for the time being, if you run any other type of case, you should be fine.

**Comment by JacobCrabill** [comment]
Should be fixed now!
