### ISSUE TITLE
About getting started

### ISSUE THREAD

**Issue by Yasien-Essam** [JacobCrabill/FlurryPP#7]
Dear Dr. Jacob,
I followed the instruction : 

`$ make release mpi=n
`
I got this message:

`make: *** No rule to make target``release'. Stop.
``
I don't know how to continue. Waiting your reply. Thank you in advance.
Regards,
Yasien

**Comment by JacobCrabill** [comment]
Hi Yasien,

Sorry about that confusion; I updated the makefile a while back but didn't update the README.  I've updated the README to have the new compilation instructions.  Just set your options in configfiles/default.config, then type 'make'.

**Comment by Yasien-Essam** [comment]
Thank you Dr. Jacob
